import React from 'react'

const Landing = () => {
  return (
    <div className='text-white mt-10 ml-5'>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iste, officia? Reiciendis quam eum natus saepe sequi, consequatur dignissimos est unde, impedit, possimus excepturi deserunt earum neque laborum aliquid accusantium nobis accusamus repellat voluptates sit veniam. Alias, distinctio totam ipsum eveniet cumque dolore eum, nihil placeat minima incidunt dolorum enim atque qui. Provident, quam. Aperiam, explicabo voluptatem sunt eos consequuntur molestiae voluptates veritatis ex quaerat possimus voluptatum eligendi, alias adipisci cupiditate, quo dolor veniam corrupti? Eligendi labore corrupti iste, voluptatum ipsa aperiam rem quam earum, consequuntur unde repellendus provident magnam nostrum itaque officiis, molestiae tempore fuga sunt nemo. Iusto, dolor delectus a commodi quasi assumenda placeat ut aperiam voluptas soluta at dolore excepturi quisquam quaerat quas voluptates nobis, enim sint fugit! Tempore nostrum dolorum vitae esse veritatis aperiam sequi excepturi eaque ex odio perspiciatis corporis inventore sint blanditiis, commodi assumenda. Earum cupiditate eos repellat dignissimos! Nesciunt at vel nulla deserunt, nobis cumque doloribus excepturi, debitis dolores quas inventore aliquid dolor ab, quisquam ducimus aperiam corrupti dolorum sunt pariatur quasi mollitia. Esse repellat nulla nam ipsa saepe vero atque. Aspernatur ducimus sapiente eum minima perferendis dignissimos perspiciatis dolor suscipit, reiciendis molestiae laudantium natus quo, debitis aperiam quod expedita quas exercitationem soluta? Voluptatum ea nisi neque earum vel enim placeat, ab nihil sed esse magnam temporibus cumque nesciunt, voluptates labore quas dolore! Quasi animi autem illum fuga a vitae nulla nobis? Nisi pariatur cum veritatis dolor laborum assumenda distinctio at quo tempora accusantium animi ipsam minus, facilis eos consequatur accusamus quisquam. Enim minima voluptatum error ea cumque perferendis temporibus animi dolorum quidem consectetur aliquam voluptatibus iusto praesentium est fugit nisi eveniet, aliquid libero. Magni sequi nam dicta at! Quidem, pariatur iusto!
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis amet quae sint obcaecati nostrum expedita cupiditate minus saepe ipsa, fuga corporis quas ducimus. Nihil eveniet libero quis enim ullam cupiditate placeat omnis itaque, odio explicabo velit quos ipsam doloremque qui dolores praesentium, et provident error earum atque dolore, ex magnam dolorum assumenda! Maxime, laboriosam dolore incidunt labore architecto, maiores minus est, amet nesciunt dignissimos sint. Quos, aliquam facilis? Sunt itaque ab nemo optio quam vitae facere mollitia fuga. Amet debitis nam, eaque culpa minus molestias voluptates ratione assumenda. Assumenda, ex. Repudiandae alias rem neque ducimus repellendus tempore quia provident, quod at eum id eligendi consequatur labore velit. Repudiandae natus eum error sit similique qui iusto ipsa, perferendis esse harum, repellat voluptates asperiores. Aspernatur accusantium nostrum dolor corporis atque delectus, amet quidem placeat odio sequi eveniet cum excepturi ipsa non quisquam fugit officiis quos quis voluptate architecto suscipit explicabo dolores provident? Quia dolorum sed quae doloremque rem magni delectus fugit voluptatum ullam, iusto dolorem neque non nemo mollitia quibusdam blanditiis animi quod temporibus. Iusto, quod assumenda recusandae tempora blanditiis deleniti? Repudiandae repellat nostrum ab officiis consectetur culpa minima dolorum aliquam, aspernatur, dolorem nam quia id sapiente. Illo voluptates nam nostrum ipsa a incidunt officia? Ut magnam dicta voluptatem ducimus. Voluptatibus pariatur laboriosam tempora assumenda rem quasi nihil consectetur sunt excepturi temporibus numquam unde fugiat enim, perspiciatis error blanditiis voluptatum cum quia dignissimos illo mollitia consequatur. Harum necessitatibus eos quidem, quaerat recusandae, enim commodi iure id non voluptatum officia ipsam eaque explicabo hic. Expedita quibusdam beatae enim soluta voluptates eligendi ipsum dolores ad. Excepturi nostrum corporis facilis. Temporibus hic maxime sapiente architecto, laboriosam facilis ipsum voluptatum dolorum amet, est unde minima? Quam quae itaque debitis harum cum suscipit beatae explicabo officia blanditiis sint quis commodi libero nobis nulla nemo quod eveniet, dicta quaerat! Reprehenderit perspiciatis eaque aliquid, quod vero blanditiis necessitatibus veniam pariatur! Iusto sint, sunt odit ipsa eum, voluptatem quam dignissimos saepe cumque itaque earum impedit sed magni doloremque! Quia, porro?
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore laboriosam, voluptatem commodi deleniti tempora officiis accusantium exercitationem ea quas veniam consequatur est voluptate iure repellendus maiores quaerat minus soluta tenetur, perspiciatis sapiente quam earum? Laboriosam voluptate id ut unde, quis debitis reprehenderit, numquam omnis dolore cupiditate, excepturi maiores! Impedit quod modi quo dignissimos placeat cupiditate optio aliquam facere amet delectus, voluptate totam ad earum? Quod molestias ad aspernatur praesentium repellendus sit nesciunt molestiae explicabo repellat et, vel dolor eius expedita animi. Quibusdam tempora debitis adipisci maxime neque illo nobis dolor, autem perspiciatis vitae saepe, incidunt repudiandae quis omnis ipsam ullam aperiam illum facilis mollitia deleniti doloremque repellat asperiores exercitationem molestias! Inventore unde nemo aperiam doloremque sed error corporis reiciendis ut ducimus, nobis explicabo vel quo iusto maiores exercitationem voluptas cum harum debitis, modi accusantium fugit illum consectetur, neque non. Suscipit qui, distinctio at a eum fugiat reiciendis incidunt, voluptas quas dignissimos voluptatum magnam numquam, architecto aperiam? Earum dolorem, deleniti rerum perferendis repellendus nihil corrupti unde minima fugiat in tempora inventore quidem ad animi dolores obcaecati iusto magni beatae. Qui quibusdam dolorum doloremque debitis ipsum est praesentium expedita! Architecto voluptatibus illo corporis itaque quasi beatae sit! Facilis, ex porro. Pariatur officiis, nulla consequuntur quidem magnam consequatur. Similique sequi eum quo earum ut optio accusamus nam autem.
    </div>
  )
}

export default Landing
